# Generated by Django 2.2.6 on 2019-11-03 22:19

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point_goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_start_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('goal_end_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('point_goal', models.PositiveIntegerField(default=0)),
                ('goal_accomplished', models.TextField(blank=True, default='no', null=True)),
                ('points_needed_for_goal_achieved', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('current_point_total_input', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('goal_health_field', models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000)),
                ('goal_metric_field', models.CharField(choices=[('activityMetric', 'Activity Metric'), ('total_points', 'Points')], default='total_points', help_text='Activity Metrics: Sleep = Hours, Water = 100oz, Clean Eating = 24hrs, Steps = Steps, Workout = Minutes', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Point_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_points', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('water_points', models.PositiveIntegerField(default=0)),
                ('workout_points', models.PositiveIntegerField(default=0)),
                ('total_points', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('clean_eating_points', models.PositiveIntegerField(default=0)),
                ('step_points', models.PositiveIntegerField(default=0)),
                ('daily_point_goal', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('up_to_date_total_points_accumulated', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_point_input_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='yyyy-mm-dd')),
                ('Hours_of_sleep', models.PositiveIntegerField(default=0)),
                ('Water_100oz', models.BooleanField(default=False)),
                ('clean_eating', models.BooleanField(default=False)),
                ('workout_intensity', models.PositiveIntegerField(default=0, help_text='input 0-4, None, light, moderate, \n            intense, super intense', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)])),
                ('workout_amount_of_time', models.PositiveIntegerField(default=0, verbose_name='Workout time (in minutes)')),
                ('steps', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
