# Generated by Django 2.2.6 on 2019-10-01 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190812_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_point_input_model',
            name='workout_intensity',
            field=models.PositiveIntegerField(default=0, help_text='input 0-4, None, light, moderate, \n            intense, super intense', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
