# Generated by Django 2.2.6 on 2019-11-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191103_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_model',
            name='sleep_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_point_input_model',
            name='Hours_of_sleep',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
