# Generated by Django 2.2.6 on 2019-10-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191001_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_goals',
            name='goal_health_field',
            field=models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000),
        ),
        migrations.AddField(
            model_name='point_goals',
            name='goal_metric_field',
            field=models.CharField(choices=[('activityMetric', 'Activity Metric'), ('total_points', 'Points')], default='total_points', max_length=10000),
        ),
    ]
