# Generated by Django 2.2.6 on 2019-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191030_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='point_goals',
            name='daily_goal',
            field=models.PositiveIntegerField(default=0, help_text='Activity Metrics: Sleep = Hours, Water = 100oz, Clean Eating = 24hrs, Steps = Steps, Workout = Minutes'),
        ),
        migrations.AlterField(
            model_name='point_goals',
            name='point_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
