# Generated by Django 2.2.6 on 2019-11-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191031_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point_goals',
            name='goal_metric_field',
            field=models.CharField(choices=[('activityMetric', 'Activity Metric'), ('total_points', 'Points')], default='total_points', help_text='Activity Metrics: Sleep = Hours, Water = 100oz, Clean Eating = 24hrs, Steps = Steps, Workout = Minutes', max_length=10000),
        ),
        migrations.AlterField(
            model_name='point_goals',
            name='point_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
