# Generated by Django 2.2.6 on 2019-11-03 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191102_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_point_input_model',
            name='Hours_of_sleep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='user_point_input_model',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='yyyy-mm-dd'),
        ),
    ]
