# Generated by Django 2.2.6 on 2019-11-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191103_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_point_input_model',
            name='Hours_of_sleep',
            field=models.FloatField(default=0),
        ),
    ]
