# Generated by Django 2.2.6 on 2019-11-03 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'idle'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='idle', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation_to_challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('end_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('challenge_health_field', models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000)),
                ('username_of_invitor', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('invitees', models.ManyToManyField(help_text='invite as many people to the challenge!', related_name='Invitation', through='challenges.Invitation_status', to=settings.AUTH_USER_MODEL)),
                ('invitor_user_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invitation_status',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Invitation_to_challenge'),
        ),
        migrations.AddField(
            model_name='invitation_status',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('end_date', models.DateField(default=django.utils.timezone.now, help_text='year-month-day')),
                ('challenge_health_field', models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000)),
                ('invitations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.Invitation_to_challenge')),
                ('participants', models.ManyToManyField(blank=True, related_name='challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
