# Generated by Django 2.2.4 on 2019-08-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20190812_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation_to_challenge',
            old_name='invitor',
            new_name='invitor_user_model',
        ),
        migrations.AddField(
            model_name='invitation_to_challenge',
            name='invitor_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
