# Generated by Django 2.2.4 on 2019-08-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_auto_20190812_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation_to_challenge',
            name='invitor_username',
        ),
    ]
