# Generated by Django 2.2.4 on 2019-08-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_invitation_to_challenge_invitor_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation_to_challenge',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
