# Generated by Django 2.2.4 on 2019-08-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_invitation_to_challenge_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation_to_challenge',
            old_name='username',
            new_name='username_of_invitor',
        ),
    ]
