# Generated by Django 2.2.4 on 2019-08-13 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20190812_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_status',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.Invitation_to_challenge'),
        ),
        migrations.AlterField(
            model_name='invitation_status',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
