# Generated by Django 2.2.4 on 2019-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_auto_20190813_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challenge_health_field',
            field=models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000),
        ),
    ]
