# Generated by Django 2.2.6 on 2019-10-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_auto_20190813_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation_to_challenge',
            name='challenge_health_field',
            field=models.CharField(choices=[('sleep_points', 'Sleep'), ('water_points', 'Water'), ('clean_eating_points', 'Clean Eating'), ('step_points', 'Steps'), ('total_points', 'Total Points'), ('workout_points', 'Workout')], default='total_points', max_length=10000),
        ),
    ]
